# Copyright (c) 2022 SIL International. MIT License.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Build flatpak w action

on:
  push:
    branches: [ org.sil.FieldWorks dev-fieldworks ]
  pull_request:
    branches: [ org.sil.FieldWorks dev-fieldworks ]
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    timeout-minutes: 180
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
      - name: "Check if it's plugged in"
        run: |
          set -xueo pipefail
          cd /tmp
          attempt=1
          while (( attempt++ < 10 )); do
            (
              wget 'https://github.com/sillsdev/flathub/releases' || exit 1
              wget 'https://api.github.com/repos/sillsdev/flathub/releases' || exit 1
              wget 'https://api.nuget.org/v3/index.json' || exit 1
              # Fetching Geckofx45 can fail even if fetching the index.json succeeds.
              wget 'https://api.nuget.org/v3-flatcontainer/Geckofx45.64.Linux/45.0.21/Geckofx45.64.Linux.45.0.21.nupkg' || exit 1
              wget 'https://flathub.org/repo/flathub.flatpakrepo' || exit 1
              wget 'https://salsa.debian.org/public' || exit 1
            ) && break
            echo "Failed attempt ${attempt}"
            cat /etc/hosts
            sudo tee -a /etc/hosts <<< '152.199.4.184 api.nuget.org'
            sleep 1m
          done
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: FieldWorks.flatpak
          manifest-path: org.sil.FieldWorks.yml
          cache: true
