# Copyright (c) 2021 SIL International. MIT License.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Build flatpak

on:
  push:
    branches: [ org.sil.FieldWorks ]
  pull_request:
    branches: [ org.sil.FieldWorks ]
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
#     container:
#       image: bilelmoussaoui/flatpak-github-actions:gnome-40
#       options: --privileged
    steps:
      - name: Fix package repositories
        run: |
          set -ueo pipefail
          ls -al /etc/apt/source*
          cat /etc/apt/sources.list
          sudo perl -pi -e 's/security.ubuntu.com/azure.archive.ubuntu.com/' /etc/apt/sources.list
      - name: Adjust disk space
        run: |
          # Disk space
          pwd
          ls -a /
          df -h
          # sudo du -sh /*  || true
          # du -sh /usr/share/dotnet /usr/local/lib/android /opt/ghc || true
          #sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          echo 'Packages using space:'
          # rpm --query --all --queryformat '%{size}\t%{name}\n' | sort --numeric-sort --reverse | head --lines=100
          dpkg-query -W -f='${Installed-Size}\t${binary:Package}\t${Version}\n' | sort --numeric-sort --reverse|head --lines=30
          sudo apt-get autoremove --assume-yes
          sudo apt-get clean
          #for package in mozjs78  dejavu-sans-fonts  adobe-source-code-pro-fonts cairo harfbuzz alsa-lib libX11; do
          #  echo removing ${package}
          #  sudo rpm -e --nodeps "${package}"
          #done
          df -h
      - uses: actions/checkout@v2
#       - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
#         with: 
#           bundle: org.sil.FieldWorks.flatpak
#           manifest-path: org.sil.FieldWorks.yml
      - name: Install flatpak dependencies
        run: |
          set -xueo pipefail
          function tryharderto() { i=0; until "$@"; do ((++i > 3)) && false
          echo >&2 Retrying ${i}; sleep 2m; done }
          set -ueo pipefail
          sudo apt-get update
          tryharderto sudo apt-get install flatpak-builder
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install flathub org.gnome.Sdk//3.36
          flatpak install flathub org.gnome.Platform//3.36
      - name: Build flatpak package
        run: |
          set -xueo pipefail
          pwd
          ls -al
          flatpak-builder --user --force-clean build-dir org.sil.FieldWorks.yml
